services:
  app:
    build: .
    env_file: .env
    ports:
      - "5000:8000"
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py
    networks:
      - delphi
    restart:
      unless-stopped
networks:
  delphi:
    external: true
