services:
  app:
    build: .
    env_file: .env
    ports:
      - "5000:8000"
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py
    networks:
      - delphi
    labels:
      - traefik.http.routers.delphi-http=Host(`delphi.sigmundus.com`)
      - traefik.http.routers.delphi-http.entrypoints=web
    restart:
      unless-stopped
networks:
  delphi:
    external: true
