services:
  app:
    build: .
    env_file: .env
    ports:
      - "5000:8000"
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py
    networks:
      - delphi
    labels:
      - traefik.enable=true
      - traefik.http.routers.delphi-http.rule=Host(`delphi.sigmundus.com`)
      - traefik.http.routers.delphi-http.entrypoints=web
      - traefik.http.services.delphi-service.loadbalancer.server.port=5000
    restart:
      unless-stopped
networks:
  delphi:
    external: true
